version: '3'

services:
  client:
    build:
      context: ./packages/mote-client
    environment:
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - "./packages/mote-client/.caddy:/root/.caddy"
  server:
    build:
      context: ./packages/mote-server
    environment:
      PORT: 4001
    ports:
      - "4001:4001"
